import streamlit as st

st.title(":thinking_face: 생각할거리")
st.divider()
st.write(":one: 피드백을 만들던 중 당연한 오답을 모델이 정확히 처리하지 못하는 것을 확인할 수 있었음")
st.write(":point_right: 학습의 과정에서 학생들이 보여줬던 반응들만 분석 가능하다는 모델의 한계를 확인 가능함")
st.write(":point_right: 일반화의 관점에서 모델의 성능을 높일 방법을 고민할 필요가 있음")
st.divider()
st.write(":two: 모델이 안정적이지 않음")
st.write(":point_right: 띄어쓰기가 바뀐다고 피드백 결과가 바뀜")
st.write(":point_right: 더 일관된 규칙의 데이터 변환이 필요해보임")
st.write(":point_right: 학생들이 작성하는 방식이나, 데이터를 변환하는 과정을 고려할 때 많은 어려움이 있을 것으로 예상")
st.divider()
st.write(":three: 학생의 학습과정을 반영한 피드백을 생성하기 어려움")
st.write(":point_right: 인공지능은 문항에 대한 답변만 가지고 피드백을 생성함")
st.write(":point_right: 같은 공란이더라도 학생이 답안을 작성하지 않은 이유가 다를 것")
st.write(":point_right: 교사의 판단과 분석이 중요할 것으로 보임")
st.divider()
st.write(":four: 실제 교육현장에서의 적용을 고려한다면 cold start problem을 고민해야할 것으로 보임")
st.write(":point_right: 거대 언어 모델 사용?")
st.divider()
st.write(":five: 모델의 성능이 높게 나오기는 했지만, 100%인 모델은 한개밖에 존재하지 않음")
st.write(":point_right: 정확도가 100%가 아닌데 학교 현장에서 사용 가능할까")
st.write(":point_right: 인공지능이 채점하는 행위를 수요자가 받아들일 수 있을지")
st.divider()

