import streamlit as st

st.title("모델")
st.divider()
st.header("1. 지식요소 모델")
st.write("모델의 input($X$) : 학생들의 응답 데이터")
st.write("모델의 output($y$) : 지식요소 + 정오답")
st.write("각 문항 별로 한 개의 모델 학습")
st.divider()
st.header("2. 오개념 모델")
st.write("모델의 input($X$) : 학생들의 응답 데이터")
st.write("모델의 output($y$) : 정오답 + 오개념")
st.write("각 문항 별로 한 개의 모델 학습")
st.divider()
st.header("3. 정오답 채점 모델")
st.write("모델의 input($X$) : 문항 정보 + 학생들의 응답 데이터")
st.write("모델의 output($y$) : 정오답")
st.write("모든 문항에 대한 정오답 채점 모델을 한 개의 모델 학습")
st.divider()
st.header("모델의 layer와 hyperparameter")
st.write("Layer : RNN, LSTM, MultiheadAttention")
st.write("Tokenizer : Sentencepiece(sp), Bertwordpiecetokenizer(bw)")
st.write("Max len : 100")
st.write("Embedding dimensioin : 100")
st.write("Hidden dimensioin : 100")
st.write("Optimizer : Adam")
st.write("Learning rate : 1e-4")
st.write("Epoch : 100")
st.write("Batch size : 16")
st.write("Virtual environment : Google Colab(cuda 그래픽카드 사용하기)")
st.write("그 외 hyperparameter에 대한 default 정보는 [github cfg](https://github.com/iss98/automatic_assessment_snumed/blob/main/cfg.py)에서 확인 가능")