import streamlit as st

st.set_page_config(layout="wide")
st.title(":desktop_computer: 모델")
st.write("수집한 데이터를 바탕으로 3가지 모델을 만듦")
st.write(":one: 지식요소 모델")
st.write(":two: 오개념 모델")
st.write(":three: 정오답 채점 모델")
st.divider()
st.header(":one: 지식요소 모델")
st.write(":black_circle: 모델의 input($X$) : 학생들의 응답 데이터")
st.write(":black_circle: 모델의 output($y$) : 지식요소 + 정오답")
st.write("각 문항 별로 한 개의 모델 학습")
st.divider()
st.header(":two: 오개념 모델")
st.write(":black_circle: 모델의 input($X$) : 학생들의 응답 데이터")
st.write(":black_circle: 모델의 output($y$) : 정오답 + 오개념")
st.write("각 문항 별로 한 개의 모델 학습")
st.divider()
st.header(":three: 정오답 채점 모델")
st.write(":black_circle: 모델의 input($X$) : 문항 정보 + 학생들의 응답 데이터")
st.write(":black_circle: 모델의 output($y$) : 정오답")
st.write("모든 문항에 대한 정오답 채점 모델을 한 개의 모델 학습")
st.divider()
st.header(":desktop_computer: 모델의 layer와 hyperparameter")
st.write("**Layer** : RNN, LSTM, MultiheadAttention")
st.write("**Tokenizer** : Sentencepiece(sp), Bertwordpiecetokenizer(bw)")
st.write("**Max len** : 100")
st.write("**Vocab size** : 문제의 길이에 따라 60개부터 140개까지 다양하게 사용")
st.write("**Embedding dimensioin** : 100")
st.write("**Hidden dimensioin** : 100")
st.write("**Optimizer** : Adam")
st.write("**Learning rate** : 1e-4")
st.write("**Epoch** : 100")
st.write("**Batch size** : 16")
st.write("**Virtual environment** : Google Colab(cuda 그래픽카드 사용하기)")
st.write(":white_check_mark: hyperparameter에 대한 default 정보는 [github cfg](https://github.com/iss98/automatic_assessment_snumed/blob/main/cfg.py)에서 확인 가능")
st.write(":white_check_mark: 모델 학습에 활용한 코드 정보는 [github repo](https://github.com/iss98/automatic_assessment_snumed)에서 확인 가능")
st.write(":white_check_mark: 모델의 학습 과정과 성능 비교를 위해 wandb를 활용")